### PR TITLE
Better slackbot moderator and fix start recording bug when reviewing

### LINKED ISSUE #9: Starting recording after stopping breaks UI
After I hit "Stop Recording" I can hit Start again, and it doesn't work so well.

image

### LINKED ISSUE #26: Add duration to slackbot moderator
Currently the slackbot moderator shows `assetId`, `playbackId`, and some actions.

slackbot-moderator

It would be good to add another field `duration`. The duration field is convenient for a moderator to have when assessing content at first glance.

### PR DESCRIPTION
**Pull request by dylanjha**
- also add some basic test coverage
- closes #26
- closes #9 

Also makes an enhancement to slackbot moderator to use storyboards instead of thumbnails, much more useful!

slackbot-moderator

### CODE REVIEW

File: lib/got-client.ts [hunk 1]
```diff
@@ -0,0 +1,9 @@
+import got, { Options } from 'got';
+
+const options = {} as Options;
+
+if (process.env.NODE_ENV === 'test') {
+  options.retry = 0;
+}
```
Comment (dylanjha) [inline lib/got-client.ts:7]: By default `got` will retry failed requests a couple times. In test env when we're using `nock` we don't really want that to happen
