### PR TITLE
fix action buttons

### LINKED ISSUE #157: Upload / record buttons missing on iOS (chrome and safari)
Viewing https://stream.new from my iPhone, I'm unable to see the `Record from camera`, `Record my screen` buttons or upload a file from device. I've tried scrolling up and down, left and right, but no luck.

Device: iPhone 14 Pro
Browsers: Chrome and Safari

Screenshot 2023-02-10 at 4 00 32 PM

### PR DESCRIPTION
**Pull request by dylanjha**
I think closes #157 

I believe in one of the upgrades of `@mux/mux-uploader` we broke some existing behavior.

Because MuxUploader in pre-1.0 release this was expected while we do some significant refactors. But I think we got a little too aggressive updating without fully QA'ing.

This still needs some cross-device QA before merging.

### CODE REVIEW

File: pages/index.tsx [hunk 1]
```diff
@@ -198,9 +193,6 @@ const Index: React.FC<Props> = () => {
         .cta {
           display: flex;
           flex-direction: column;
-          position: absolute;
-          right: 0;
-          bottom: 0;
```
Comment (dylanjha) [inline pages/index.tsx:203]: removing this fixed FF

**Review by gkatsev — APPROVED** [review]
